dependencies {
	compileOnly project(":modules:portalops-agent-content")
	compileOnly project(":modules:portalops-agent-management")
	compileOnly project(":modules:portalops-agent-search")
	compileOnly project(":modules:portalops-agent-site")
	compileOnly group: "com.liferay.portal", name: "release.portal.api"
	compileOnly project(":modules:portalops-agent-user")
	compileOnly project(":modules:portalops-ai-api")
	compileOnly project(":modules:portalops-api")
	compileOnly project(":modules:portalops-assistant-api")
	compileOnly project(":modules:portalops-llm-spi")
}
